export default{
  THEME_CHANGE:"THEME_CHANGE",//改变主题色
  THEME_INIT:"THEME_INIT ",//初始化主题色
  POPULAR_REFRESH:"POPULAR_REFRESH",//最热下拉刷新
  POPULAR_REFRESH_FAIL:"POPULAR_REFRESH_FAIL",//最热请求失败
  POPULAR_REFRESH_SUCCESS:"POPULAR_REFRESH_SUCCESS",//最热请求成功
  POPULAR_LOAD_MORE_SUCCESS:"POPULAR_LOAD_MORE_SUCCESS",//最热上拉加载更多成功
  POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",//最热上拉加载更多失败
  FLUSH_POPULAR_FAVORITE:"FLUSH_POPULAR_FAVORITE",//刷新最热模块收藏状态
  TRENDING_FLUSH_FAVORITE:"TRENDING_FLUSH_FAVORITE",//刷新趋势模块收藏状态
  TRENDING_REFRESH:"TRENDING_REFRESH", //趋势下拉刷新
  TRENDING_REFRESH_FAIL:"TRENDING_REFRESH_FAIL",//趋势请求失败
  TRENDING_REFRESH_SUCCESS:"TRENDING_REFRESH_SUCCESS",//趋势请求成功
  TRENDING_LOAD_MORE_SUCCESS:"TRENDING_LOAD_MORE_SUCCESS",//趋势上拉加载更多成功
  TRENDING_LOAD_MORE_FAIL:"TRENDING_LOAD_MORE_FAIL",//趋势上拉加载更多失败
  FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",//请求收藏数据
  FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",//请求收藏数据成功
  FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",//请求收藏数据失败
  LANGUAGE_LOAD_SUCCESS:"LANGUAGE_LOAD_SUCCESS",//加载语言成功
}
